import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>My First NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center p-6'>
        <h1 className="text-3xl font-light underline">Hello world</h1>
        <ul>
          <li><a href="/damian">Página de Damián</a></li>
          <li><a href="/brenda">Página de Brenda</a></li>
        </ul>
      </main>
    </>
  )
}
