import Head from 'next/head'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>My First NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center p-6'>
        <h1 className="text-3xl font-light underline mb-6 p-6 bg-gray-500 mr-auto rounded-xl">Hello World</h1>
        {/* Usando variável de ambiente na frase abaixo */}
        Eu sou o {process.env.NEXT_PUBLIC_NOME}
        <ul className='flex flex-col gap-4'>
          <li><a href="/damian">Página de Damián</a></li>
          <li><a href="/brenda">Página de Brenda</a></li>
          <li><a href="/valentina">Página de Valentina</a></li>
          <li><a href="/isis">Página de Isis</a></li>
          <li><a href="/lana">Página de Lana</a></li>
          <li><a href="/tyson">Página de Tyson</a></li>
        </ul>
        {/* <Script strategy='afterInteractive'>
          {`window.alert('Carreguei')`}
        </Script> */}
      <footer className=' mt-10 flex flex-col gap-5'>
        <a href='/blog'>EXERCÍCIO SSG - BLOG</a>
        <a href='/album'>EXERCÍCIO CSR - ALBUM</a>
        <a href='/todo'>EXERCÍCIO SSR - LISTA DE TAREFAS</a>
      </footer>
      </main>
    </>
  )
}
